---
version: "3.3"
services:
  postgres-hn:
    container_name: postgres-hn
    image: timescale/timescaledb-ha:pg14-latest
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/script:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
    environment:
      POSTGRES_MULTIPLE_DATABASES: hackernews
      POSTGRES_PASSWORD: password
      POSTGRES_UID: 1000
      POSTGRES_GID: 1000
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    ports:
      - "3003:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:password@postgres-hn:5432/hackernews
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3003
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - postgres-hn
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "3004:8080"
    expose:
      - "3004"
    environment:
      API_URL: http://localhost:3003/